# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/rentflow
spring.data.mongodb.database=rentflow

# Server
server.port=8081

# App name
spring.application.name=rentflow-backend
