# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://EndUser:sangi19@rent-go.d7jwbii.mongodb.net/rentflow?appName=Rent-Go
spring.data.mongodb.database=rentflow

# JWT configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Server
server.port=8081

# App name
spring.application.name=rentflow-backend
